### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Trilarion** [Mekire/cabbages-and-kings#2]
Hi,

Does the project has an open source license allowing sharing and mofication like GPL, MIT, BSD, ... or is it more like "all rights reserved"? If it isn't licensed like this, is such a step planned in the future?

I could not find specific information about the license status in the code or in the issues but the project looks promising.

Thanks and kind regards.

**Comment by Mekire** [comment]
Sorry, forgot I never added one.  I didn't realize there was any interest in this project.  I have added the MIT license and a brief readme in the licences folder.

**Comment by Trilarion** [comment]
Thanks for responding and for adding a license so quickly.
